schema_version: 1

context:
  name: fandango
  version: 16.0.3
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fandango-${{ version }}.tar.gz
  sha256: 73b59d213db51665869e19677f00547fc389f00ceb6a9d805d8dd9603e516653

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fandango = fandango.scripts.fandango_cli:main
      - tango2csv = fandango.scripts.tango2csv:main
      - tango2json = fandango.scripts.tango2json:main
      - tango_host = fandango.scripts.tango_host:main
      - tango_monitor = fandango.scripts.tango_monitor:main
      - tango_servers = fandango.scripts.tango_servers:main

requirements:
  host:
    - python 3.10.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - fandango
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - fandango --help

about:
  summary: Simplify the configuration of big Tango control systems
  license: LGPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.com/tango-controls/fandango
  documentation: https://pythonhosted.org/fandango/

extra:
  recipe-maintainers:
    - sergirubio
    - ovallcorba
